version: '3'

services:
  database:
    image: mysql:5.6
    restart: always
    volumes:
    - ./data:/var/lib/mysql
    - ./car_rental.sql:/docker-entrypoint-initdb.d/app.sql:ro
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: car_rental
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_USER: root
      PMA_PASSWORD: password
      PMA_HOST: database
    ports:
      - 8081:80

  api-server:
    image: kolcsonzo-api
    build: ./
    ports:
      - 8080:80
      - 8443:443
    environment:
      RUNTIME: DOCKER
      DB_HOST: database
      DB_NAME: car_rental
      DB_USER: root
      DB_PASSWORD: password
