# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1-browsers
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install dependencies...
          command: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
        
      - run:
          name: "Build docker image"
          command: docker build -t clearcodesolutions/kolcsonzo-api:$CIRCLE_SHA1 .
      
      - deploy:
          name: "Push docker image(s) to Docker Hub"
          command: |
            case $CIRCLE_BRANCH in
            "master")
              DOCKER_RELEASE_TAG=latest
              ;;
            "develop")
              DOCKER_RELEASE_TAG=edge
              ;;
            esac

            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push clearcodesolutions/kolcsonzo-api:$CIRCLE_SHA1

            if [ ! -z "$DOCKER_RELEASE_TAG" ]
            then
              docker tag clearcodesolutions/kolcsonzo-api:$CIRCLE_SHA1 clearcodesolutions/kolcsonzo-api:$DOCKER_RELEASE_TAG
              docker push clearcodesolutions/kolcsonzo-api:$DOCKER_RELEASE_TAG
            fi

            if [ ! -z "$CIRCLE_TAG" ]
            then
              docker tag clearcodesolutions/kolcsonzo-api:$CIRCLE_SHA1 clearcodesolutions/kolcsonzo-api:$CIRCLE_TAG
              docker push clearcodesolutions/kolcsonzo-api:$CIRCLE_TAG
            fi